name: adonis_websok_null_safety
description: Adonis (adonisjs) high level web sockets. Implements the websocket protocol specified by adonisjs.
version: 1.0.2
author: João Pedro Freire
homepage: https://github.com/djpfs/
repository: https://github.com/djpfs/AdonisWebsokNullSafety
documentation: https://github.com/djpfs/AdonisWebsokNullSafety
issue_tracker: https://github.com/djpfs/AdonisWebsokNullSafety/issues
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  websokNullSafety:
    git:
      url: https://github.com/djpfs/websokNullSafety.git

dev_dependencies:
  test: ^1.9.4
